(()=>{
const activate=(button,selector)=>document.querySelectorAll(selector).forEach(x=>x.classList.toggle('active',x===button));
const feedback=message=>typeof toast==='function'&&toast(message);
const openAction=(title,message,label,target)=>{modal.classList.add('open');modal.querySelector('h2').textContent=title;modal.querySelector('p').textContent=message;modal.querySelector('b').textContent='✓ Personalized to your Career Profile';let action=modal.querySelector('.modal-action');if(!action){action=document.createElement('button');action.className='primary modal-action';modal.appendChild(action)}action.textContent=label;action.onclick=()=>{modal.classList.remove('open');if(target)go(target)}};
document.querySelector('.profile-card')?.addEventListener('click',()=>go('twin'));document.querySelector('.avatar')?.addEventListener('click',()=>go('twin'));document.querySelector('.head-actions button:not(.avatar)')?.addEventListener('click',()=>openAction('Your career updates','Market demand increased, one saved role changed, and an evidence item is ready for review.','Open Job Market','market'));
document.querySelectorAll('.skill').forEach(skill=>skill.addEventListener('click',()=>{skill.classList.toggle('skill-selected');openAction(skill.childNodes[0].textContent.trim(),`${skill.querySelector('small')?.textContent||'Profile skill'}. Add evidence, complete an assessment or place this skill in your plan.`,'Build evidence','experience')}));
const roles={'Recommended for you':[['Transformation Program Director','84%'],['AI Transformation Director','68%'],['Chief Operating Officer','79%']],'IT & Technology':[['Technology Transformation Director','86%'],['Enterprise Architect','74%'],['Chief Technology Officer','57%']],Healthcare:[['Digital Health Programme Director','73%'],['Healthcare Transformation Lead','81%'],['Clinical Technology Advisor','62%']],Finance:[['Finance Transformation Director','78%'],['FinTech Programme Lead','76%'],['Chief Operating Officer','79%']],Management:[['Transformation Director','84%'],['Portfolio Director','88%'],['Strategy & Operations Director','75%']],'All careers':[['Transformation Program Director','84%'],['AI Transformation Director','68%'],['Portfolio Director','88%']]};
document.querySelectorAll('.career-switch button').forEach(tab=>tab.addEventListener('click',()=>{activate(tab,'.career-switch button');const cards=[...document.querySelectorAll('#roles .path')];(roles[tab.textContent.trim()]||roles['Recommended for you']).forEach((role,i)=>{if(cards[i]){cards[i].querySelector('h2').textContent=role[0];cards[i].querySelector('.path-top strong').innerHTML=`${role[1]}<small>ready</small>`}});feedback(`${tab.textContent.trim()} pathways loaded`)}));
document.querySelectorAll('.gap-tabs button').forEach(tab=>tab.addEventListener('click',()=>{activate(tab,'.gap-tabs button');const type=tab.textContent.trim().toLowerCase().split(' ')[0];document.querySelectorAll('.gap-list article').forEach(item=>item.hidden=type!=='all'&&!item.querySelector('.gap-type')?.textContent.toLowerCase().includes(type));if(![...document.querySelectorAll('.gap-list article')].some(x=>!x.hidden)){document.querySelectorAll('.gap-list article').forEach(x=>x.hidden=false);feedback('Showing the closest matching evidence gaps')}}));
document.querySelectorAll('.radar-filters button').forEach((filter,index)=>{const sets=index===0?['🇳🇱 Netherlands⌄','🇩🇪 Germany⌄','🇬🇧 United Kingdom⌄','🇮🇳 India⌄']:index===1?['Technology & consulting⌄','Healthcare⌄','Finance⌄','All industries⌄']:['Next 24 months⌄','Next 12 months⌄','Next 3 years⌄'];let n=0;filter.addEventListener('click',()=>{filter.textContent=sets[++n%sets.length];feedback('Market signals refreshed')})});document.querySelector('.opportunity-map .panel-head button')?.addEventListener('click',()=>go('world'));
const scenarios=[['+68%','78%','AI capability increases projected market value and opens higher-growth leadership paths.'],['−8%','82%','Without new evidence, market position may weaken as role expectations change.'],['+91%','61%','The CTO route offers higher upside but needs deeper strategy, architecture and commercial proof.']];document.querySelectorAll('.scenario-toggle button').forEach((tab,i)=>tab.addEventListener('click',()=>{activate(tab,'.scenario-toggle button');const chart=document.querySelector('.future-chart'),data=scenarios[i];chart.querySelector('.chart-head>div>b').textContent=data[0];chart.querySelector('.confidence b').textContent=data[1];document.querySelector('.simulation-note').textContent=data[2]+' Forecasts are illustrative, not guarantees.';chart.classList.toggle('negative-scenario',i===1);feedback('Future scenario recalculated')}));
document.querySelectorAll('.world-filters button').forEach((filter,index)=>{const sets=index===0?['All professions⌄','Technology⌄','Healthcare⌄','Finance⌄']:['All regions⌄','Europe⌄','North America⌄','India & APAC⌄'];let n=0;filter.addEventListener('click',()=>{filter.textContent=sets[++n%sets.length];feedback('Global signals updated')})});document.querySelectorAll('.people-tabs button').forEach(tab=>tab.addEventListener('click',()=>activate(tab,'.people-tabs button')));
const saved=JSON.parse(localStorage.getItem('careerNavigatorTasks')||'[]');document.querySelectorAll('.task-check').forEach((button,index)=>{if(saved.includes(index)){button.classList.add('done');button.textContent='✓'}button.addEventListener('click',()=>setTimeout(()=>localStorage.setItem('careerNavigatorTasks',JSON.stringify([...document.querySelectorAll('.task-check')].map((x,i)=>x.classList.contains('done')?i:null).filter(x=>x!==null))),0))});
document.getElementById('analyzeJob')?.addEventListener('click',()=>{const text=document.getElementById('jdText').value.trim();if(text.length<40){feedback('Please paste a fuller job description');return}const terms=['lead','transformation','stakeholder','budget','ai','governance','strategy','delivery','benefits','operating'],score=Math.min(94,64+terms.filter(x=>text.toLowerCase().includes(x)).length*3),result=document.getElementById('matchResult');result.querySelector('.match-circle').innerHTML=`${score}<small>%</small>`;result.querySelector('h2').textContent=score>=82?'Strong potential match':score>=72?'Promising match':'Stretch opportunity';result.querySelector('p').textContent=`Your profile shows evidence for ${Math.round(score/4.5)} of 22 core expectations.`;result.classList.add('result-updated')});
document.querySelectorAll('.market-links a').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();document.getElementById(link.getAttribute('href')?.slice(1))?.scrollIntoView({behavior:'smooth'})}));
document.querySelectorAll('.demo').forEach(button=>button.addEventListener('click',()=>{const title=button.textContent.replace(/[＋→]/g,'').trim()||'Career action';let action=modal.querySelector('.modal-action');if(!action){action=document.createElement('button');action.className='primary modal-action';modal.appendChild(action)}action.textContent='Save and continue';action.onclick=()=>{const history=JSON.parse(localStorage.getItem('careerNavigatorActivity')||'[]');history.unshift({title,completed_at:new Date().toISOString()});localStorage.setItem('careerNavigatorActivity',JSON.stringify(history.slice(0,50)));modal.classList.remove('open');feedback(`${title} saved to your Career Profile`)}}));
const planCopy=document.querySelector('.plans .section-intro p');if(planCopy)planCopy.textContent='Choose the level of guidance and career intelligence that fits your journey. No payment is collected in this early-access release.';
})();
