(()=>{
'use strict';
if(window.__CAREER_IMPACT_INDEX_LOADED__)return;window.__CAREER_IMPACT_INDEX_LOADED__=true;
const STORE='careerNavigatorImpactIndexV1',PROFILE='careerNavigatorUserProfileV1',CONSENT='ciiConsentV1',VERSION='1.0';
const defs=[
 {id:'experience',name:'Professional experience',weight:15,hint:'Career progression and scope'},
 {id:'leadership',name:'Leadership scope',weight:15,hint:'Teams, decisions and transformation'},
 {id:'business',name:'Business impact',weight:15,hint:'Value, savings and commercial outcomes'},
 {id:'governance',name:'Board & governance',weight:10,hint:'Formal and advisory accountability'},
 {id:'innovation',name:'Innovation & IP',weight:10,hint:'Patents, products and original work'},
 {id:'education',name:'Education & learning',weight:10,hint:'Relevant and recent development'},
 {id:'influence',name:'Industry influence',weight:10,hint:'Credible public contribution'},
 {id:'community',name:'Community impact',weight:10,hint:'Documented sustained outcomes'},
 {id:'future',name:'Future readiness',weight:5,hint:'Skills for the next role'}
];
const statusFactor={verified:1,partial:.75,self:.5},statusLabel={verified:'Verified',partial:'Partially verified',self:'Self-declared'};
const escape=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}};
const profile=()=>read(PROFILE,{});
let state=read(STORE,{stage:'leader',evidence:[],challenges:[],updatedAt:null});
if(!Array.isArray(state.evidence))state.evidence=[];
const save=()=>{state.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(state))};
const navAnchor=document.querySelector('.nav[data-view="twin"]');if(!navAnchor||document.getElementById('impact'))return;
const nav=document.createElement('button');nav.className='nav';nav.dataset.view='impact';nav.innerHTML='<span>CII</span>Impact Index';navAnchor.after(nav);
const view=document.createElement('section');view.className='view impact-view';view.id='impact';view.innerHTML=`
 <div class="impact-hero"><div><span class="eyebrow">CAREER IMPACT INDEX&trade;</span><h1>Your impact, backed by evidence.</h1><p>A voluntary professional-development assessment of leadership, contribution, innovation, influence and future readiness. Not an employment eligibility decision.</p><div class="impact-hero-actions"><button class="impact-light" id="impactAdd">+ Add evidence</button><button class="impact-clear" id="impactMethod">How scoring works</button><button class="impact-clear" id="impactShare">Share summary</button><button class="impact-clear" id="impactExport">Export data</button></div></div><div class="impact-total"><div class="impact-ring"><strong id="impactScore">--<small>/100</small></strong></div><span>CAREER IMPACT INDEX</span><small id="impactBenchmark">Complete your evidence register</small></div></div>
 <article class="panel impact-controls"><label>Benchmark group <select id="impactStage"><option value="executive">Executive / C-suite</option><option value="leader">Senior leader</option><option value="manager">People manager</option><option value="specialist">Experienced specialist</option><option value="early">Early-career professional</option><option value="graduate">Student / graduate</option><option value="founder">Founder / entrepreneur</option><option value="researcher">Researcher / innovator</option><option value="social">Social-impact leader</option></select></label><span class="confidence-chip">Evidence confidence: <b id="impactConfidence">0%</b></span></article>
 <div class="impact-empty" id="impactEmpty"><span>â—ˆ</span><h2>Build your evidence-based assessment</h2><p>Your score starts only after you add professional evidence. Claims remain self-declared until independently reviewed.</p><button class="primary" id="impactEmptyAdd">Add my first evidence</button></div>
 <div class="impact-layout"><article class="panel impact-dimensions"><h2>Impact dimensions</h2><p class="impact-sub">A deterministic engine applies published, career-stage-adjusted weights.</p><div id="impactRows"></div></article><article class="panel impact-evidence"><div class="impact-evidence-head"><div><h2>Evidence register</h2><p class="impact-sub">Inspect, edit or challenge every claim.</p></div><button class="outline" id="impactAddSmall">+ Add</button></div><div class="impact-evidence-list" id="impactEvidence"></div><div class="impact-detail" id="impactDetail">Select a claim to see its source and scoring contribution.</div></article></div>
 <div class="impact-insights"><article class="panel"><h3>Professional impact statement</h3><p id="impactStatement">Add evidence to generate an evidence-led statement.</p></article><article class="panel"><h3>Best development opportunity</h3><p id="impactOpportunity">Complete your evidence register to reveal the dimension with the greatest development potential.</p></article></div>
 <div class="impact-safeguard"><b>Important:</b> Participation is opt-in. Sensitive characteristics are excluded. You can inspect, correct, delete and challenge evidence. Employers must not use this index as the sole basis for hiring or promotion. Method version ${VERSION}.</div>`;
document.querySelector('main').appendChild(view);
const dashboardEntry=document.createElement('article');dashboardEntry.className='impact-dashboard-entry';dashboardEntry.innerHTML='<div><span>CII</span><section><small>NEW · EVIDENCE-BASED ASSESSMENT</small><h2>Career Impact Index&trade;</h2><p>Measure your documented professional impact and see exactly how every evidence item contributes.</p></section></div><button type="button">Open my Impact Index →</button>';const dashboard=document.getElementById('dashboard');const dashboardAnchor=dashboard?.querySelector('.score-grid');if(dashboardAnchor)dashboardAnchor.after(dashboardEntry);
const modal=document.createElement('div');modal.className='impact-modal';modal.id='impactModal';modal.innerHTML='<article class="impact-consent" id="impactModalCard"></article>';document.body.appendChild(modal);
const card=()=>document.getElementById('impactModalCard');
function weights(){return defs.map(d=>{let w=d.weight;if(['graduate','early'].includes(state.stage)&&d.id==='governance')w=0;if(state.stage==='graduate'&&d.id==='experience')w=8;if(state.stage==='graduate'&&d.id==='education')w=22;if(state.stage==='researcher'&&d.id==='innovation')w=20;if(state.stage==='founder'&&d.id==='business')w=22;if(state.stage==='social'&&d.id==='community')w=22;return{...d,weight:w}})}
function assessment(){const ws=weights(),scores={};let confidencePoints=0;defs.forEach(d=>{const items=state.evidence.filter(e=>e.dimension===d.id);if(!items.length){scores[d.id]=0;return}const weighted=items.reduce((s,e)=>s+Number(e.strength)*statusFactor[e.status],0);scores[d.id]=Math.round(weighted/items.length);confidencePoints+=items.reduce((s,e)=>s+({verified:100,partial:70,self:35}[e.status]||0),0)});const active=ws.filter(d=>d.weight>0),totalWeight=active.reduce((s,d)=>s+d.weight,0),score=state.evidence.length?Math.round(active.reduce((s,d)=>s+scores[d.id]*d.weight,0)/totalWeight):null,confidence=state.evidence.length?Math.round(confidencePoints/state.evidence.length):0;return{ws,scores,score,confidence}}
function render(){const a=assessment();document.getElementById('impactStage').value=state.stage;document.getElementById('impactScore').innerHTML=`${a.score??'--'}<small>/100</small>`;document.getElementById('impactConfidence').textContent=`${a.confidence}%`;document.querySelector('.impact-ring').style.background=`conic-gradient(#51d5aa 0 ${a.score||0}%,#ffffff2d ${a.score||0}%)`;document.getElementById('impactBenchmark').textContent=a.score===null?'Complete your evidence register':`${state.evidence.length} evidence item${state.evidence.length===1?'':'s'} Â· assessed ${new Date().toLocaleDateString()}`;document.getElementById('impactEmpty').classList.toggle('hidden',state.evidence.length>0);document.querySelector('.impact-layout').classList.toggle('hidden',!state.evidence.length);document.querySelector('.impact-insights').classList.toggle('hidden',!state.evidence.length);
 document.getElementById('impactRows').innerHTML=a.ws.map(d=>`<div class="impact-row"><label>${d.name}<small>${Math.round(d.weight/a.ws.reduce((s,x)=>s+x.weight,0)*100)}% weight Â· ${d.hint}</small></label><i><em style="width:${a.scores[d.id]}%"></em></i><b>${a.scores[d.id]}</b></div>`).join('');
 document.getElementById('impactEvidence').innerHTML=state.evidence.length?state.evidence.map((e,i)=>`<button data-evidence="${i}"><span class="evidence-state ${e.status}">${statusLabel[e.status]}</span><b>${escape(e.title)}</b><small>${escape(defs.find(d=>d.id===e.dimension)?.name)} Â· ${escape(e.source||'No source supplied')}</small></button>`).join(''):'<p class="impact-no-evidence">No evidence added yet.</p>';
 document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>showEvidence(+b.dataset.evidence,b));
 if(state.evidence.length){const ranked=defs.map(d=>({d,score:a.scores[d.id],count:state.evidence.filter(e=>e.dimension===d.id).length})).filter(x=>x.count).sort((x,y)=>y.score-x.score),strong=ranked.slice(0,2).map(x=>x.d.name.toLowerCase()),weak=[...defs].sort((x,y)=>a.scores[x.id]-a.scores[y.id]).find(d=>a.ws.find(w=>w.id===d.id)?.weight>0);const p=profile();document.getElementById('impactStatement').textContent=`${p.name||'This professional'} demonstrates the strongest documented impact in ${strong.join(' and ')}. The assessment is based on ${state.evidence.length} user-approved evidence item${state.evidence.length===1?'':'s'} with ${a.confidence}% evidence confidence.`;document.getElementById('impactOpportunity').textContent=`Strengthen ${weak.name.toLowerCase()} by adding a specific outcome, your personal contribution and an independently reviewable source.`}
 save()}
function showConsent(){card().innerHTML='<span class="eyebrow">VOLUNTARY ASSESSMENT</span><h2>Before we assess your impact</h2><p>You choose whether to participate. The assessment uses only professional information you provide and evidence you approve.</p><ul><li>No sensitive characteristics are inferred or scored.</li><li>You can inspect, change and delete every item.</li><li>A low confidence score means limited evidence, not low ability.</li></ul><footer><button class="cancel">Not now</button><button class="accept">I understand, continue</button></footer>';openModal();card().querySelector('.cancel').onclick=closeModal;card().querySelector('.accept').onclick=()=>{localStorage.setItem(CONSENT,JSON.stringify({accepted:true,date:new Date().toISOString(),version:VERSION}));closeModal();addEvidence()}}
function addEvidence(index=null){if(!read(CONSENT,{}).accepted){showConsent();return}const current=index===null?{title:'',dimension:'experience',strength:60,status:'self',source:'',detail:''}:state.evidence[index];card().innerHTML=`<button class="impact-modal-close" aria-label="Close">Ã—</button><span class="eyebrow">${index===null?'ADD':'EDIT'} PROFESSIONAL EVIDENCE</span><h2>${index===null?'What impact can you support?':'Update this evidence item'}</h2><form id="impactForm"><label>Evidence title<input name="title" required maxlength="120" value="${escape(current.title)}" placeholder="e.g. Led a regional service transformation"></label><label>Impact dimension<select name="dimension">${defs.map(d=>`<option value="${d.id}" ${current.dimension===d.id?'selected':''}>${d.name}</option>`).join('')}</select></label><label>Strength of documented outcome <span id="impactStrengthValue">${current.strength}/100</span><input name="strength" id="impactStrength" type="range" min="10" max="100" step="5" value="${current.strength}"></label><label>Evidence source<input name="source" maxlength="240" value="${escape(current.source)}" placeholder="URL, document name or organisation record"></label><label>What was your contribution and measurable result?<textarea name="detail" required maxlength="1200" placeholder="Describe your role, scope and outcome">${escape(current.detail)}</textarea></label><div class="impact-form-note">New and edited evidence is labelled <b>Self-declared</b>. Independent review is required for verified status.</div><footer><button type="button" class="cancel">Cancel</button><button class="accept" type="submit">${index===null?'Add evidence':'Save changes'}</button></footer></form>`;openModal();card().querySelector('.impact-modal-close').onclick=closeModal;card().querySelector('.cancel').onclick=closeModal;const range=document.getElementById('impactStrength');range.oninput=()=>document.getElementById('impactStrengthValue').textContent=`${range.value}/100`;document.getElementById('impactForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const item={id:current.id||crypto.randomUUID(),title:data.title.trim(),dimension:data.dimension,strength:Number(data.strength),status:index===null?'self':current.status,source:data.source.trim(),detail:data.detail.trim(),createdAt:current.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(index===null)state.evidence.push(item);else state.evidence[index]=item;closeModal();render();notify(index===null?'Evidence added and score recalculated':'Evidence updated and score recalculated')}}
function showEvidence(index,button){document.querySelectorAll('[data-evidence]').forEach(x=>x.classList.toggle('active',x===button));const e=state.evidence[index],contribution=Math.round(e.strength*statusFactor[e.status]);document.getElementById('impactDetail').innerHTML=`<b>${statusLabel[e.status]}</b> Â· contributes ${contribution}/100 to this dimension after evidence weighting<br><br>${escape(e.detail)}<br><br><small>Source: ${escape(e.source||'Not supplied')}<br>Updated: ${new Date(e.updatedAt).toLocaleDateString()}</small><div class="impact-detail-actions"><button class="outline" id="impactEdit">Edit</button><button class="outline" id="impactChallenge">Challenge status</button><button class="impact-delete" id="impactDelete">Delete</button></div>`;document.getElementById('impactEdit').onclick=()=>addEvidence(index);document.getElementById('impactChallenge').onclick=()=>challenge(index);document.getElementById('impactDelete').onclick=()=>removeEvidence(index)}
function challenge(index){const e=state.evidence[index];card().innerHTML=`<button class="impact-modal-close">Ã—</button><span class="eyebrow">HUMAN REVIEW REQUEST</span><h2>Challenge evidence status</h2><p>${escape(e.title)}</p><form id="challengeForm"><label>Explain what should be corrected<textarea name="reason" required maxlength="800" placeholder="Describe the error or additional verification source"></textarea></label><footer><button type="button" class="cancel">Cancel</button><button class="accept">Submit challenge</button></footer></form>`;openModal();card().querySelector('.impact-modal-close').onclick=closeModal;card().querySelector('.cancel').onclick=closeModal;document.getElementById('challengeForm').onsubmit=event=>{event.preventDefault();state.challenges.push({evidenceId:e.id,reason:new FormData(event.currentTarget).get('reason').trim(),status:'pending',createdAt:new Date().toISOString()});save();closeModal();notify('Challenge saved for human review')}}
function removeEvidence(index){if(!confirm('Delete this evidence item? This will recalculate your score.'))return;state.evidence.splice(index,1);document.getElementById('impactDetail').textContent='Select a claim to see its source and scoring contribution.';render();notify('Evidence deleted and score recalculated')}
function method(){card().innerHTML='<button class="impact-modal-close">Ã—</button><span class="eyebrow">METHODOLOGY 1.0</span><h2>Transparent, deterministic scoring</h2><p>Each evidence item has an outcome-strength value. Verification applies a fixed evidence factor: verified 100%, partially verified 75%, self-declared 50%. Dimension results are averaged, then career-stage weights calculate the final index.</p><p>Evidence Confidence is separate: verified evidence contributes 100, partial evidence 70 and self-declared evidence 35. Missing dimensions score zero so the report never invents impact.</p><p><b>Important:</b> only an independent review workflow can mark evidence as verified.</p>';openModal();card().querySelector('.impact-modal-close').onclick=closeModal}
async function share(){const a=assessment(),p=profile(),text=`Career Impact Index: ${a.score??'Not yet assessed'}/100\nEvidence Confidence: ${a.confidence}%\nBenchmark: ${state.stage}\nEvidence items: ${state.evidence.length}\n\nVoluntary professional-development assessment Â· Method ${VERSION} Â· Not an employment eligibility decision.`;try{await navigator.clipboard.writeText(text);notify('Shareable summary copied')}catch{card().innerHTML=`<button class="impact-modal-close">Ã—</button><h2>Shareable summary</h2><textarea class="impact-share-text">${escape(text)}</textarea>`;openModal();card().querySelector('.impact-modal-close').onclick=closeModal}}
function exportData(){const payload={product:'Career Navigator AI â€“ Career Impact Index',methodVersion:VERSION,exportedAt:new Date().toISOString(),profile:{name:profile().name||'',currentRole:profile().currentRole||'',targetRole:profile().targetRole||''},benchmark:state.stage,assessment:assessment(),evidence:state.evidence,challenges:state.challenges,notice:'Voluntary professional-development assessment. Not an employment eligibility decision.'},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`career-impact-index-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);notify('Impact Index data exported')}
function openModal(){modal.classList.add('open')}function closeModal(){modal.classList.remove('open')}function notify(msg){if(typeof toast==='function')toast(msg)}
function openImpact(){if(typeof go==='function')go('impact');if(!read(CONSENT,{}).accepted)showConsent()}nav.addEventListener('click',openImpact);dashboardEntry.querySelector('button').addEventListener('click',openImpact);document.getElementById('impactStage').onchange=e=>{state.stage=e.target.value;render();notify('Benchmark updated and score recalculated')};document.getElementById('impactAdd').onclick=()=>addEvidence();document.getElementById('impactAddSmall').onclick=()=>addEvidence();document.getElementById('impactEmptyAdd').onclick=()=>addEvidence();document.getElementById('impactMethod').onclick=method;document.getElementById('impactShare').onclick=share;document.getElementById('impactExport').onclick=exportData;modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
render();
})();
