function initCareerUsability(){
  if(new URLSearchParams(location.search).has('app')){const site=document.getElementById('marketSite');if(site)site.style.display='none';document.querySelector('.shell')?.classList.remove('product-hidden')}
  const dashboard=document.getElementById('dashboard');
  if(!document.querySelector('.mobile-dock'))document.body.insertAdjacentHTML('beforeend','<nav class="mobile-dock" aria-label="Mobile navigation"><button data-go="dashboard"><span>⌂</span>Home</button><button data-go="roadmap"><span>↗</span>My Plan</button><button data-go="jobmatch"><span>▤</span>Job Match</button><button data-go="advisor"><span>✦</span>Ask AI</button></nav>');
  dashboard.innerHTML=`
    <div class="home-welcome"><div><span class="eyebrow">YOUR CAREER COMMAND CENTRE</span><h1>Good morning, Jami.</h1><p>Focus on one meaningful step at a time. We have translated your profile, goal and market signals into a clear plan.</p></div><button class="primary" data-go="advisor">Ask your AI advisor <span>→</span></button></div>
    <section class="journey-status"><div class="journey-copy"><span class="status-chip">ON TRACK</span><p class="journey-label">YOUR CHOSEN GOAL</p><h2>Transformation Director</h2><p class="journey-sub">You have strong leadership and delivery experience. The shortest path is to prove AI-enabled transformation and commercial ownership.</p><div class="journey-route"><div><span>NOW</span><b>Senior Program Manager</b></div><i><em style="width:71%"></em></i><div class="destination"><span>NEXT</span><b>Transformation Director</b></div></div><div class="journey-actions"><button class="primary" data-go="roadmap">Continue my plan</button><button class="soft" data-go="gaps">Why am I 71% ready?</button><button class="text-action" data-go="roles">Change my goal</button></div></div><div class="readiness-dial"><div><strong>71</strong><small>%</small></div><b>READY</b><span>↑ 6% this month</span></div></section>
    <section class="next-step"><div class="step-number">01</div><div class="step-main"><span class="eyebrow">YOUR BEST NEXT ACTION</span><h2>Complete your AI leadership baseline</h2><p>15 minutes · Free · Improves your readiness by approximately 4%</p><div class="step-value"><span>Why this matters</span><p>AI governance appears in 42% more target-role descriptions, but your profile contains limited proof.</p></div></div><button class="primary useful-action" data-action="baseline">Start now <span>→</span></button></section>
    <div class="home-grid"><section class="home-panel weekly-plan"><div class="home-panel-head"><div><span class="eyebrow">THIS WEEK</span><h2>Three steps that move you forward</h2></div><button data-go="roadmap">View full plan</button></div><div class="week-task"><button class="task-check" aria-label="Mark AI baseline complete">1</button><div><b>Complete AI leadership baseline</b><p>Today · 15 minutes</p></div><strong>+4%</strong></div><div class="week-task"><button class="task-check" aria-label="Mark case study complete">2</button><div><b>Turn your ERP programme into a case study</b><p>Tomorrow · 45 minutes</p></div><strong>+6%</strong></div><div class="week-task"><button class="task-check" aria-label="Mark interview practice complete">3</button><div><b>Practise a director-level interview</b><p>This week · 20 minutes</p></div><strong>+3%</strong></div></section>
    <section class="home-panel clarity-card"><span class="eyebrow">WHAT HELPS · WHAT HOLDS YOU BACK</span><h2>Your readiness, simply explained</h2><div class="clarity-row good"><span>✓</span><div><b>Leadership & governance</b><p>Your strongest advantage</p></div><strong>91%</strong></div><div class="clarity-row"><span>↑</span><div><b>AI-enabled delivery</b><p>Highest-value gap</p></div><strong>56%</strong></div><div class="clarity-row"><span>＋</span><div><b>Evidence quality</b><p>Five skills need proof</p></div><strong>63%</strong></div><button class="soft full" data-go="gaps">See the complete breakdown</button></section></div>
    <section class="value-strip"><article><span>◎</span><div><b>84% role match</b><p>Transformation Director is your strongest realistic next move.</p></div><button data-go="roles">Explore</button></article><article><span>↗</span><div><b>Market demand is rising</b><p>AI governance and value realization are growing fastest.</p></div><button data-go="market">See signals</button></article><article><span>▤</span><div><b>One profile improvement</b><p>Your CV underplays commercial ownership and outcomes.</p></div><button data-go="studio">Improve CV</button></article></section>
    <section class="quick-tools"><div class="home-panel-head"><div><span class="eyebrow">QUICK TOOLS</span><h2>What would you like to do?</h2></div></div><div><button data-go="jobmatch"><span>82%</span><b>Check a job</b><small>Paste a role and see your honest match</small></button><button data-go="twin"><span>42</span><b>Review my profile</b><small>Skills, proof and career identity</small></button><button data-go="experience"><span>＋</span><b>Build experience</b><small>Create credible portfolio evidence</small></button><button data-go="advisor"><span>✦</span><b>Ask Career AI</b><small>Get an explained recommendation</small></button></div></section>`;

  const labels={dashboard:['⌂','Home'],twin:['◎','My Profile'],roles:['◇','Career Options'],gaps:['◔','My Skill Gaps'],roadmap:['↗','My Action Plan'],experience:['✦','Build Experience'],jobmatch:['▤','Check a Job'],studio:['◫','CV & Interview'],market:['⌁','Job Market'],dna:['⬡','Career DNA'],gps:['⌖','Career GPS'],future:['◫','Future Simulator'],life:['♥','Life & Career'],agents:['✦','AI Mentors'],world:['◎','Global Opportunities'],advisor:['◉','Ask Career AI']};
  document.querySelectorAll('.nav[data-view]').forEach(nav=>{const item=labels[nav.dataset.view];if(!item)return;const badge=nav.querySelector(':scope>b')?.outerHTML||'';nav.innerHTML=`<span>${item[0]}</span>${item[1]}${badge}`;nav.setAttribute('aria-label',item[1])});
  document.querySelectorAll('.side nav>p').forEach((p,i)=>p.textContent=i===0?'START HERE':i===1?'BUILD YOUR FUTURE':p.textContent);
  const futureLabel=document.querySelector('.future-label');
  if(futureLabel){futureLabel.textContent='MORE CAREER TOOLS';const toggle=document.createElement('button');toggle.className='tools-toggle';toggle.innerHTML='<span>＋</span> Show advanced tools';futureLabel.before(toggle);document.querySelectorAll('.future-nav').forEach(n=>n.classList.add('advanced-hidden'));toggle.onclick=()=>{const open=toggle.classList.toggle('open');document.querySelectorAll('.future-nav').forEach(n=>n.classList.toggle('advanced-hidden',!open));futureLabel.classList.toggle('advanced-hidden',!open);toggle.innerHTML=open?'<span>−</span> Hide advanced tools':'<span>＋</span> Show advanced tools'};futureLabel.classList.add('advanced-hidden')}

  document.addEventListener('click',e=>{const goButton=e.target.closest('[data-go]');if(goButton&&typeof go==='function'){e.preventDefault();go(goButton.dataset.go)}const check=e.target.closest('.task-check');if(check){check.classList.toggle('done');check.textContent=check.classList.contains('done')?'✓':check.getAttribute('aria-label').includes('baseline')?'1':check.getAttribute('aria-label').includes('case')?'2':'3';toast(check.classList.contains('done')?'Great work — progress saved':'Task marked incomplete')}const action=e.target.closest('.useful-action');if(action){modal.classList.add('open');modal.querySelector('h2').textContent='AI leadership baseline';modal.querySelector('p').textContent='Answer 8 practical questions to understand how confidently you can lead AI-enabled change. It takes about 15 minutes and produces a personalized action plan.';modal.querySelector('b').textContent='Ready when you are — your progress will be saved'}});

  document.querySelectorAll('.demo').forEach(button=>button.addEventListener('click',()=>{const name=button.textContent.trim().replace(/[＋→]/g,'').trim();modal.querySelector('h2').textContent=name||'Interactive workflow';modal.querySelector('p').textContent=contextualMessage(name);modal.querySelector('b').textContent='Your work will be saved to your Career Profile'}));
  function contextualMessage(name){const n=name.toLowerCase();if(n.includes('evidence'))return'Add a work example, outcome, document or credential. Career Navigator will connect it to the skills it proves.';if(n.includes('assessment'))return'Complete a short evidence-based assessment. You will see exactly how the result changes your readiness.';if(n.includes('experience'))return'Choose a capability to practise and receive a realistic project brief that creates portfolio-ready proof.';if(n.includes('clinical'))return'Explore safeguarded pathways for clinical leadership, informatics, research, digital health and medical affairs.';return`Continue with “${name}” in this interactive product workflow.`}

  const search=document.querySelector('.search');const input=search?.querySelector('input');
  if(search&&input){search.insertAdjacentHTML('beforeend','<div class="smart-results"><small>QUICK NAVIGATION</small><button data-search-go="roles">Explore career options</button><button data-search-go="gaps">See skill gaps</button><button data-search-go="jobmatch">Check a job description</button><button data-search-go="advisor">Ask Career AI</button></div>');const results=search.querySelector('.smart-results');input.placeholder='Find a tool or ask a career question…';input.addEventListener('focus',()=>results.classList.add('show'));input.addEventListener('input',()=>{const q=input.value.toLowerCase();results.querySelectorAll('button').forEach(b=>b.hidden=q&&!b.textContent.toLowerCase().includes(q))});input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const q=input.value.trim();if(q){go('advisor');setTimeout(()=>{advisorInput.value=q;ask(q)},50)}results.classList.remove('show')}});results.addEventListener('click',e=>{const b=e.target.closest('[data-search-go]');if(b){go(b.dataset.searchGo);results.classList.remove('show')}});document.addEventListener('click',e=>{if(!search.contains(e.target))results.classList.remove('show')})}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initCareerUsability);else initCareerUsability();
