import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
function routeModel(agentType:string,message:string){const complexity=message.length>700||/compare|strategy|executive|transition|trade.?off|five.?year/i.test(message);if(agentType==='career'||agentType==='mentor'||complexity)return{model:Deno.env.get('OPENAI_MODEL_SOL')||'gpt-5.6-sol',effort:'high'};if(agentType==='skills'||agentType==='jobs'||agentType==='market'||agentType==='evidence')return{model:Deno.env.get('OPENAI_MODEL_TERRA')||'gpt-5.6-terra',effort:'medium'};return{model:Deno.env.get('OPENAI_MODEL_LUNA')||'gpt-5.6-luna',effort:'low'}}
const prompts:Record<string,string>={
 career:'You are a career strategy specialist. Recommend realistic adjacent roles, compare trade-offs and give concrete next actions. Never promise employment.',
 skills:'You are a skills intelligence specialist. Identify strengths, missing evidence, valuable emerging capabilities and declining skills. Explain all conclusions.',
 evidence:'You are an evidence specialist. Turn genuine work into credible STAR-style evidence. Never invent experience or achievements.',
 jobs:'You are a job-match specialist. Assess requirements against provided evidence, identify mandatory gaps and prepare an honest application strategy.',
 learning:'You are a learning-plan specialist. Build efficient learn-practise-prove-present plans within stated time and budget.',
 market:'You are a career market intelligence specialist. Explain demand signals and uncertainty. Do not invent live vacancies, salaries or statistics.',
 mentor:'You coordinate career, leadership, learning and wellbeing guidance into one sustainable plan.'
};
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const token=req.headers.get('Authorization');if(!token)throw new Error('Authentication required');const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:token}}});const {data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)throw new Error('Invalid session');const body=await req.json();const agentType=String(body.agent_type||'');const message=String(body.message||'').trim();if(!prompts[agentType]||message.length<2||message.length>6000)throw new Error('Invalid agent request');const context=body.context&&typeof body.context==='object'?body.context:{};const route=routeModel(agentType,message),model=route.model;const {data:run,error:insertError}=await supabase.from('agent_runs').insert({user_id:user.id,agent_type:agentType,input:message,context,status:'running',model}).select('id').single();if(insertError)throw insertError;const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${Deno.env.get('OPENAI_API_KEY')}`,'Content-Type':'application/json'},body:JSON.stringify({model,reasoning:{effort:route.effort},input:[{role:'system',content:`${prompts[agentType]} Act as one specialist within a coordinated career team. Use only supplied evidence; never fabricate experience, jobs, salaries or market statistics. State assumptions and missing evidence. Give: Assessment, Evidence used, Reasoning, Next 3 actions, Risks and uncertainty. Be direct, practical and supportive.`},{role:'user',content:`Career context:\n${JSON.stringify(context)}\n\nUser request:\n${message}`}],max_output_tokens:1600})});if(!response.ok)throw new Error(`AI service returned ${response.status}`);const result=await response.json();const answer=result.output_text||result.output?.flatMap((item:any)=>item.content||[]).filter((x:any)=>x.type==='output_text').map((x:any)=>x.text).join('\n')||'No answer returned.';await supabase.from('agent_runs').update({answer,status:'completed',summary:answer.slice(0,240),completed_at:new Date().toISOString()}).eq('id',run.id);return new Response(JSON.stringify({run_id:run.id,answer,model}),{headers:{...cors,'Content-Type':'application/json'}})}catch(error){return new Response(JSON.stringify({error:error.message||'Agent failed'}),{status:400,headers:{...cors,'Content-Type':'application/json'}})}});
